FROM ubuntu:24.04

ENV APP_VERSION=1.0

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y --no-install-recommends build-essential git cmake autoconf libtool pkg-config libboost-all-dev net-tools netcat-openbsd && rm -rf /var/lib/apt/lists/*

WORKDIR /equityExchange

COPY CMakeLists.txt inputFile.csv main.cpp DepthBook.* Exchange.* OrderTracker.* UDPServer.* .

RUN cmake . && make

EXPOSE 1234

CMD ["./equityexchangetest", "inputFile.csv"]
 
#COPY entrypoint.sh /equityExchange/entrypoint.sh
#COPY equityexchangetest /equityExchange/equityexchangetest


#RUN chmod +x /equityExchange/entrypoint.sh #/equityExchange/equityexchangetest

#CMD ["./entrypoint.sh"]
